name: "Safe Service Sync"
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Safe Service Sync"
        uses: rmeissner/safe-service-monitor-gh-action@main
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          safe-address: '0x94D998c2Cb35bD4388D1D5Ed71992bF4a802d7a9'
          service-url: 'https://safe-transaction.rinkeby.gnosis.io'
