name: "Safe Tx Simulation"
on: [ push ]

jobs:
  simulator:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=value;]$(echo ${GITHUB_REF#refs/heads/})"
        id: target
      - name: "Safe Tx Simulation"
        uses: rmeissner/safe-simulator-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-url: ${{ secrets.JSON_RPC_NODE }}
          check-target: ${{ steps.target.outputs.value }}
          safe-address: '0x94D998c2Cb35bD4388D1D5Ed71992bF4a802d7a9'
          service-url: 'https://safe-transaction.rinkeby.gnosis.io'
          fail-on-unknown-delegatecall: 'false'
          # branch should not be protected
          branch: 'main'
